baseURL = "https://brtknr.github.io/"
title = "brtknr"
theme = "hugo-coder"
languageCode = "en"
defaultContentLanguage = "en"
paginate = 20
pygmentsStyle = "bw"
pygmentsCodeFences = true
pygmentsCodeFencesGuessSyntax = true
enableEmoji = true
# Enable Disqus comments
# disqusShortname = "brtknr"

[params]
author = "Bharat Kunwar"
description = "random interests"
keywords = "artificial intelligence, distributed consensus, agent based modelling, network science and vegan options"
info = ["Software Masseur"]
avatarURL = "images/avatar.jpg"
#gravatar = "brtknr@bath.edu"
footerContent = ""
dateFormat = "January 2, 2006"
hideFooter = false
hideCredits = false
hideCopyright = false
since = 1989
# Git Commit in Footer, uncomment the line below to enable it
commit = "https://github.com/brtknr/brtknr.github.io/tree/"
# Right To Left, shift content direction for languagues such as Arabic
rtl = false
# Specify light/dark colorscheme
# Supported values:
# "auto" (use preference set by browser)
# "dark" (dark background, light foreground)
# "light" (light background, dark foreground) (default)
colorScheme = "auto"
# Hide the toggle button, along with the associated vertical divider
hideColorSchemeToggle = false
# Series see also post count
maxSeeAlsoItems = 5
# Enable Twemoji
enableTwemoji = false
# Custom CSS
customCSS = []
# Custom SCSS
customSCSS = []
# Custom JS
customJS = ["https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js?config=TeX-AMS-MML_HTMLorMML"]

# If you want to use fathom(https://usefathom.com) for analytics, add this section
# [params.fathomAnalytics]
# siteID = "ABCDE"
# serverURL = "analytics.example.com" # Default value is cdn.usefathom.com, overwrite this if you are self-hosting

# If you want to use plausible(https://plausible.io) for analytics, add this section
# [params.plausibleAnalytics]
# domain = "example.com"
# serverURL = "analytics.example.com" # Default value is plausible.io, overwrite this if you are self-hosting or using a custom domain

# If you want to use goatcounter(https://goatcounter.com) for analytics, add this section
# [params.goatCounter]
# code = "code"

# If you want to use Cloudflare Web Analytics(https://cloudflare.com) for analytics, add this section
# [params.cloudflare]
# token = "token"

# If you want to use Matomo(https://matomo.org) for analytics, add this section
# [params.matomo]
# siteID = "ABCDE" # Default value is "1", overwrite this if you are cloud-hosting
# serverURL = "analytics.example.com" # For cloud-hosting, use provided URL, e.g. example.matomo.cloud

# If you want to use Google Tag Manager(https://analytics.google.com/) for analytics, add this section
# [params.googleTagManager]
# id = "gid"

# If you want to implement a Content-Security-Policy, add this section
[params.csp]
childsrc = ["'self'"]
fontsrc = ["'self'", "https://fonts.gstatic.com", "https://cdn.jsdelivr.net/"]
formaction = ["'self'"]
framesrc = [
  "'self'",
  "https://disqus.com/"
]
imgsrc = [
  "'self'",
  "https://c.disquscdn.com/",
  "https://referrer.disqus.com/",
]
objectsrc = ["'none'"]
stylesrc = [
  "'self'",
  "'unsafe-inline'",
  "https://referrer.disqus.com/",
  "https://c.disquscdn.com/",
  "https://fonts.googleapis.com/",
  "https://cdn.jsdelivr.net/"
]
scriptsrc = [
  "'self'",
  "'unsafe-inline'",
  "https://cdnjs.cloudflare.com/",
  "https://c.disquscdn.com/",
  "https://brtknr.disqus.com/",
  "https://www.google-analytics.com"
]
prefetchsrc = [
  "'self'",
  "https://c.disquscdn.com/",
  "https://disqus.com/"
]
# connect-src directive â€“ defines valid targets for to XMLHttpRequest (AJAX), WebSockets or EventSource
connectsrc = ["'self'", "https://www.google-analytics.com"]

[taxonomies]
category = "categories"
series = "series"
tag = "tags"
author = "authors"

[[params.social]]
name = "Github"
icon = "fa fa-github"
weight = 1
url = "https://github.com/brtknr/"

[[params.social]]
name = "Gitlab"
icon = "fa fa-gitlab"
weight = 2
url = "https://gitlab.com/brtknr/"

[[params.social]]
name = "Twitter"
icon = "fa fa-twitter"
weight = 3
url = "https://twitter.com/brtknr/"

[[params.social]]
name = "LinkedIn"
icon = "fa fa-linkedin"
weight = 4
url = "https://www.linkedin.com/in/brtknr/"

[[params.social]]
name = "CV"
icon = "fa fa-file-pdf-o"
weight = 5
url = "cv.pdf"
type = "application/pdf"

[[params.social]]
name = "RSS"
icon = "fa fa-rss"
weight = 6
url = "index.xml"
type = "application/rss+xml"

[languages.en]
languageName = ":uk:"

[[languages.en.menu.main]]
name = "About"
weight = 1
url = "about/"

[[languages.en.menu.main]]
name = "Posts"
weight = 2
url = "posts/"
